### PR TITLE
Use the new wheel config section

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by sigmavirus24** [comment]
It seems even pip has not adopted this. How new is this?

cc @dstufft

**Comment by graingert** [comment]
@sigmavirus24 they have: https://github.com/pypa/pip/blob/develop/setup.cfg#L4-L5

**Comment by graingert** [comment]
it's been bdist_wheel for a little while, let's see what happens https://github.com/pypa/pip/pull/3158

**Comment by graingert** [comment]
You can see the docs here: https://wheel.readthedocs.org/en/latest/#defining-the-python-version

**Comment by graingert** [comment]
They merged it: https://github.com/pypa/pip/pull/3158#event-424843924

**Comment by dan-blanchard** [comment]
Seems reasonable to me.

**Comment by sigmavirus24** [comment]
Test failures are unrelated.

**Pull request merged**
