### PR TITLE
Change enum classes to be capitalized

### PR DESCRIPTION
**Pull request by dan-blanchard**

### CODE REVIEW

**Comment by polyzen** [comment]
Bisected a detection issue to this commit. With the following snippet:

```
f = open('.vim/vimrc', 'rb')
bytes_seq = f.read()
chardet.detect(bytes_seq)
```

Before: `{'confidence': 1.0, 'encoding': 'ascii'}`
After: `{'confidence': 0.0, 'encoding': None, 'language': None}`

**Comment by polyzen** [comment]
Seems I forgot to hit the comment button yesterday.. Fixed in 3.0.3!

**Comment by dan-blanchard** [comment]
Glad to hear it!

**Comment by polyzen** [comment]
This is actually still an issue.

Requests 2.17.3 pointed out the chardet version I had installed was 2.3.0. Perhaps the pypi package for 3.0.3 at the time actually packaged 2.3.0?

**Comment by dan-blanchard** [comment]
I'm not sure what you mean. I've never manually removed and replaced a package on PyPI, and 3.0.3 on PyPI is definitely 3.0.3.

**Comment by polyzen** [comment]
I've deleted the sources since, so cannot verify, but either way it was 2.3.0 that had worked for me and not 3.0.3.

**Comment by polyzen** [comment]
[This](https://github.com/Kuniwak/vint/issues/146) has more details on the issue, and [these](https://github.com/polyzen/dotfiles/blob/common/.vim/vimrc#L38-L39) are apparently the lines that cause fault

**Comment by polyzen** [comment]
Should I file a new issue for this?

**Comment by polyzen** [comment]
The issue was fixed (or worked around?) with https://github.com/Kuniwak/vint/pull/248.

**Pull request merged**
