### PR TITLE
Add blacklist of orders to langturkishmodel (Windows-1254)

### PR DESCRIPTION
**Pull request by nwestbury**
Based off [Windows-1254](https://en.wikipedia.org/wiki/Windows-1254), there are some characters that aren't allowed in the encoding but it is possible to still use that encoding. For example, the utf-8 string 'abÏa'  (0x61-0x62-0xc3-0x8f-0x61) is detected as 'Windows-1254' but it contains the character 0x8f which is invalid in this encoding so it shouldn't detected as 'Windows-1254'.

This change adds a `-1` order for characters that aren't in the encoding so situations like the above don't happen (or very rarely because of the `typical_positive_ratio`). I'm open to suggestions if there is a better way to blacklist certain characters.

Might fix issue [#148](https://github.com/chardet/chardet/issues/148)

### CODE REVIEW

**Comment by nwestbury** [comment]
Too slow

**Comment by robert-d-schultz** [comment]
Why was this closed? The issue still persists, even in version 4.0.0.

**Comment by nwestbury** [comment]
Given that the maintainers haven't had a chance to look at this for 4 months, I doubt they ever will. This might also not be a good solution anyways.

**Comment by robert-d-schultz** [comment]
They should at least disable the Turkish models.
Thanks for trying though!

**Pull request closed without merging**
